services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  NITSAN\NsEventManager\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'
    

  NITSAN\NsEventManager\Controller\EventController:
    arguments:
      $eventRepository: '@NITSAN\NsEventManager\Domain\Repository\EventRepository'
      $persistenceManager: '@TYPO3\CMS\Extbase\Persistence\Generic\PersistenceManager'
  

  # NITSAN\NsEventManager\Controller\EventController:
  #   tags:
  #     - name: frontend.asset
  #       file: 'EXT:your_extension/Resources/Public/JavaScript/myscript.js'
  #       type: javascript
  #       position: footer
