services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  
  NITSAN\NsEventManager\EventListener\LoggerEventListener:
    tags:
      - name: event.listener
        identifier: 'ns_event_manager/extension_activated'

  